-- Customers
INSERT INTO customers (customer_id, first_name, last_name) VALUES('MILLMAN_JESSICA', 'Jessica', 'Millman');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('SMITH_PAUL', 'Paul', 'Smith');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('STAFMAN_BRIAN', 'Brian', 'Stafman');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('BROWN_RACHEL', 'Rachel', 'Brown');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('JONES_TAYLOR', 'Talylor', 'Jones');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('JOHNSON_ANNE', 'Anne', 'Johnson');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('WILLIAMS_ADRIENNE', 'Adrienne', 'Williams');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('GARCIA_LARRY', 'Larry', 'Garcia');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('MILLER_MITCH', 'Mitch', 'Miller');
INSERT INTO customers (customer_id, first_name, last_name) VALUES('DAVIS_JASON', 'Jason', 'Davis');

-- Dress
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Florence', 'strapless', 100.00, 1);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Rome', 'v-neck', 200.00, 2);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Venice', 'fit and flare', 130.00, 3);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Milan', 'round neck', 220.00, 4);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Verona', 'mini', 115.00, 5);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Palermo', 'maxi', 250.00, 6);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Siena', 'ruched', 150.00, 7);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Como', 'shift', 180.00, 8);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Amalfi', 'pencil', 190.00, 9);
INSERT INTO dress (dress_id, dress_style, price, customer_fk) VALUES('Sicily', 'wrap', 130.00, 1);

-- Color
INSERT INTO color (color_name, color_id) VALUES('Popcorn Yellow', 'POPCORN_YELLOW');
INSERT INTO color (color_name, color_id) VALUES('Outer Space', 'OUTER_SPACE');
INSERT INTO color (color_name, color_id) VALUES('Sea Green', 'SEA_GREEN');
INSERT INTO color (color_name, color_id) VALUES('Razzle Dazzle Rose', 'RAZZLE_DAZZLE_ROSE');
INSERT INTO color (color_name, color_id) VALUES('Cotton Candy', 'COTTON_CANDY');
INSERT INTO color (color_name, color_id) VALUES('Blue Bell', 'BLUE_BELL');
INSERT INTO color (color_name, color_id) VALUES('Vivid Violet', 'VIVID_VIOLET');
INSERT INTO color (color_name, color_id) VALUES('Denim', 'DENIM');
INSERT INTO color (color_name, color_id) VALUES('Electric Lime', 'ELECTRIC_LIME');
INSERT INTO color (color_name, color_id) VALUES('Desert Sand', 'DESERT_SAND');

-- Color Options
INSERT INTO color_options (color_fk, dress_fk) VALUES (1, 1);
INSERT INTO color_options (color_fk, dress_fk) VALUES (1, 2);
INSERT INTO color_options (color_fk, dress_fk) VALUES (1, 3);
INSERT INTO color_options (color_fk, dress_fk) VALUES (1, 4);
INSERT INTO color_options (color_fk, dress_fk) VALUES (1, 5);
INSERT INTO color_options (color_fk, dress_fk) VALUES (1, 6);
INSERT INTO color_options (color_fk, dress_fk) VALUES (1, 7);
INSERT INTO color_options (color_fk, dress_fk) VALUES (1, 8);
INSERT INTO color_options (color_fk, dress_fk) VALUES (2, 10);
INSERT INTO color_options (color_fk, dress_fk) VALUES (2, 9);
INSERT INTO color_options (color_fk, dress_fk) VALUES (2, 8);
INSERT INTO color_options (color_fk, dress_fk) VALUES (2, 7);
INSERT INTO color_options (color_fk, dress_fk) VALUES (2, 6);
INSERT INTO color_options (color_fk, dress_fk) VALUES (2, 5);
INSERT INTO color_options (color_fk, dress_fk) VALUES (2, 4);
INSERT INTO color_options (color_fk, dress_fk) VALUES (3, 7);
INSERT INTO color_options (color_fk, dress_fk) VALUES (3, 3);
INSERT INTO color_options (color_fk, dress_fk) VALUES (3, 2);
INSERT INTO color_options (color_fk, dress_fk) VALUES (3, 6);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 10);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 9);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 8);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 7);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 6);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 5);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 4);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 3);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 2);
INSERT INTO color_options (color_fk, dress_fk) VALUES (4, 1);
INSERT INTO color_options (color_fk, dress_fk) VALUES (5, 10);
INSERT INTO color_options (color_fk, dress_fk) VALUES (5, 8);
INSERT INTO color_options (color_fk, dress_fk) VALUES (5, 1);
INSERT INTO color_options (color_fk, dress_fk) VALUES (6, 2);
INSERT INTO color_options (color_fk, dress_fk) VALUES (6, 4);
INSERT INTO color_options (color_fk, dress_fk) VALUES (6, 9);
INSERT INTO color_options (color_fk, dress_fk) VALUES (6, 3);
INSERT INTO color_options (color_fk, dress_fk) VALUES (6, 5);
INSERT INTO color_options (color_fk, dress_fk) VALUES (6, 8);
INSERT INTO color_options (color_fk, dress_fk) VALUES (7, 2);
INSERT INTO color_options (color_fk, dress_fk) VALUES (7, 5);
INSERT INTO color_options (color_fk, dress_fk) VALUES (7, 6);
INSERT INTO color_options (color_fk, dress_fk) VALUES (8, 10);
INSERT INTO color_options (color_fk, dress_fk) VALUES (8, 7);
INSERT INTO color_options (color_fk, dress_fk) VALUES (8, 6);
INSERT INTO color_options (color_fk, dress_fk) VALUES (8, 1);
INSERT INTO color_options (color_fk, dress_fk) VALUES (8, 4);
INSERT INTO color_options (color_fk, dress_fk) VALUES (8, 3);
INSERT INTO color_options (color_fk, dress_fk) VALUES (8, 2);
INSERT INTO color_options (color_fk, dress_fk) VALUES (9, 1);
INSERT INTO color_options (color_fk, dress_fk) VALUES (9, 2);
INSERT INTO color_options (color_fk, dress_fk) VALUES (9, 3);
INSERT INTO color_options (color_fk, dress_fk) VALUES (9, 4);
INSERT INTO color_options (color_fk, dress_fk) VALUES (9, 5);
INSERT INTO color_options (color_fk, dress_fk) VALUES (10, 10);
INSERT INTO color_options (color_fk, dress_fk) VALUES (10, 9);
INSERT INTO color_options (color_fk, dress_fk) VALUES (10, 8);
INSERT INTO color_options (color_fk, dress_fk) VALUES (10, 7);
INSERT INTO color_options (color_fk, dress_fk) VALUES (10, 6);
